version: "3.9"

services:
  backend:
    build:
      context: ../backend
    ports:
      - "8000:8000"
    env_file:
      - ../backend/.env
    environment:
      - PYTHONPATH=src
    depends_on:
      - frontend

  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:80"  # Map frontend to port 80 inside the nginx container
    environment:
      - REACT_APP_BACKEND_BASE_URL=http://backend:8000
